# Name of website
title: novathesis LaTeX template

# Description of website
description: A LaTeX template for thesis, dissertations and similar monography-like documents

# Your name to show in the footer
author: João M. Lourenço

# logo
logo: NOVAthesisFiles/Images/novathesis-logo.jpg

show_downloads: true
theme: jekyll-theme-minimal